### ISSUE TITLE
批次表标记已完成，其他爬虫进程正在检查任务表是否有未完成的任务，本进程跳过检查，继续等待

### ISSUE THREAD

**Issue by lscool66** [Boris-code/feapder#104]
批次爬虫，多个爬虫进程，任务都完成会提示如下，并执行结束爬虫方法，请问这是正常现象吗，好像是会互相去检测任务表

批次表标记已完成，其他爬虫进程正在检查任务表是否有未完成的任务，本进程跳过检查，继续等待

**Comment by Boris-code** [comment]
> 批次爬虫，多个爬虫进程，任务都完成会提示如下，并执行结束爬虫方法，请问这是正常现象吗，好像是会互相去检测任务表
> 
> 批次表标记已完成，其他爬虫进程正在检查任务表是否有未完成的任务，本进程跳过检查，继续等待

正常
