### ISSUE TITLE
我这边获取页面数据是通过cookie,调用后台接口的方式拿到数据，现在有两个问题

### ISSUE THREAD

**Issue by TheEros** [Boris-code/feapder#105]
我这边获取页面数据是通过调用后台接口的方式拿到数据，现在有两个问题:
1.每个账户的cookie,去get 请求后台接口获取返回值，怎么在代码里循环cookie请求数据？
2.每次请求会获取到新的set cookie怎么拿到？

**Comment by Boris-code** [comment]
> 我这边获取页面数据是通过调用后台接口的方式拿到数据，现在有两个问题:
> 1.每个账户的cookie,去get 请求后台接口获取返回值，怎么在代码里循环cookie请求数据？
> 2.每次请求会获取到新的set cookie怎么拿到？

框架里的request、response 支持第三方库 requests 的所有操作
取cookie
```
response.cookies.get_dict()
```
设置cookie
```
request.cookies = {} # cookie 值
```

怎么循环取？ 你可以搞个队列啊
