### ISSUE TITLE
对于反爬取

### ISSUE THREAD

**Issue by huangwenyan1225** [Boris-code/feapder#11]
很多网站反爬取 爬出来html 不是很完整  配置mimproxy ajax js请求没触发 用selenium就没问题  是不是需要加些配置？

**Comment by Boris-code** [comment]
> 很多网站反爬取 爬出来html 不是很完整 配置mimproxy ajax js请求没触发 用selenium就没问题 是不是需要加些配置？

你说的这种应该是ajax请求，动态渲染的，建议直接走接口请求

关于要不要支持浏览器渲染，现在可以自己调用selenium下载，写法如下
```
def start_requests(self):
    yield feapder.Request("https://www.baidu.com", auto_request=False)

def parse(self, request, response):
    # response 为None， 需要自己去下载
    pass
```

后续可以考虑在框架里支持
