### ISSUE TITLE
关于为爬虫名添加限制或者检查的建议

### ISSUE THREAD

**Issue by RecluseXU** [Boris-code/feapder#12]
我个人在学习使用新的框架的时候，喜欢为每一步知识设置 如 `0_hello_world` 之类的文件(夹)名用来区分  
数字是为了让系统自动排序文件，让它更好看  

![86c99a0f78ac64672516008fc564e48](https://user-images.githubusercontent.com/27330694/110791909-ba363580-82ad-11eb-8aa2-8125f71b311c.png)
在尝试创建数字开头的爬虫后，发现由于爬虫名称与代码相关，生成的代码如类名，不可使用数字开头，导致一些很容易被修复的错误  
建议于代码中添加简单的检查，或者在文档中注明项目名取名须知

**Comment by RecluseXU** [comment]
>项目名会被用于代码生成，请按照python命名标准为项目命名

**Comment by Boris-code** [comment]
> 我个人在学习使用新的框架的时候，喜欢为每一步知识设置 如 `0_hello_world` 之类的文件(夹)名用来区分
> 数字是为了让系统自动排序文件，让它更好看
> 
> ![86c99a0f78ac64672516008fc564e48](https://user-images.githubusercontent.com/27330694/110791909-ba363580-82ad-11eb-8aa2-8125f71b311c.png)
> 在尝试创建数字开头的爬虫后，发现由于爬虫名称与代码相关，生成的代码如类名，不可使用数字开头，导致一些很容易被修复的错误
> 建议于代码中添加简单的检查，或者在文档中注明项目名取名须知

已支持检查爬虫名是否合法，提交已合并
