### ISSUE TITLE
不支持 Python3.10 

### ISSUE THREAD

**Issue by Mr-xn** [Boris-code/feapder#123]
Python3.10 运行项目提示 ,来自这个文件：`feapder/core/parser_control.py`
报错：
 `ImportError: cannot import name 'Iterable' from 'collections' (/usr/local/Cellar/python@3.10/3.10.0_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/collections/__init__.py)`

> 使用3.9无此问题

**Comment by Boris-code** [comment]
支持了
