### ISSUE TITLE
我们来比比，看谁代码少，你可以指定爬任何网站？你这个框架无法指定qps爬虫

### ISSUE THREAD

**Issue by ydf0509** [Boris-code/feapder#133]
1、你这个爬虫框架代码文件多，要在很多个文件之间来回切换写代码代码多，我这是单文件爬虫
这是爬汽车之家 列表页新闻和详情页内容的demo
https://function-scheduling-distributed-framework.readthedocs.io/zh_CN/latest/articles/c8.html

你可以选择任意网站我们来进行对比，看谁代码少看谁写得快？

2、你这个无法无视网站服务端响应耗时，持续达到每秒爬8次网页的需求。你需要补上qps功能

https://function-scheduling-distributed-framework.readthedocs.io/zh_CN/latest/articles/c4.html#qps-qps

当flask_veiw_mock 接口耗时0.1秒时候,在python输出控制台可以看到，10秒钟就运行结束了，控制台每秒打印了80次hello world，严重超频10倍了不符合需求
当flask_veiw_mock 接口耗时刚好精确等于1秒时候,在python输出控制台可以看到，100秒钟运行结束了，控制台每秒打印了8次hello world，只有当接口耗时刚好精确等于1秒时候，并发数量才符合qps需求
当flask_veiw_mock 接口耗时10秒时候,在python输出控制台可以看到，需要1000秒钟运行结束，控制台每隔10秒打印8次hello world，严重不符合持续每秒打印8次的目的。
由此可见，用设置并发数量来达到每秒请求8次flask的目的非常困难，99.99%的情况下服务端没那么巧刚好耗时1秒。

天真的人会说根据函数耗时大小，来设置并发数量，这可行吗？
```
有人会说，为了达到8qps目的，当函数里面sleep 0.1 时候他开1线程，那你这样仍然超频啊，你是每1秒钟打印10次了超过了8次。
当sleep 0.01 时候，为了达到8qps目的，就算你开1线程，那不是每1秒钟打印100次hello？你不会想到开0.08个线程个线程来实现控频吧？
当sleep 10秒时候，为了8qps目的，你开80线程，那这样是控制台每隔10秒打印80次hello，我要求的是控制台每一秒都打印8次hello，没告诉你是每隔10秒打印80次hello吧？还是没达到目的。
如果函数里面是sleep 0.005 0.07 0.09 1.3 2.7 7 11 13这些不规则无法整除的数字？请问你是如何一一计算精确开多少线程来达到8qps的？
如果flask网站接口昨天是3秒的响应时间，今天变成了0.1秒的响应时间，你的线程池数量不做变化，代码不进行重启，请问你如何做到自适应无视请求耗时，一直持续8qps的目的？
固定并发数量大小就是定速巡航不够智能前车减速会撞车，qps自适应控频那就是acc自适应巡航了，自动调整极端智能，压根无需提前测算预估函数需要耗时多久(接口响应耗时多久)。
所以综上所述,如果你有控频需求，你想用并发数量来达到控频目的，那是不可能的。
```

**Comment by Super-ye** [comment]
你这么牛，你咋还没上天呢？你不行不代表别人不行，你不行不代表你不刑，时而刑时而不行，你到底是刑还是不行？上天，你滴刑滴不行？

**Comment by ydf0509** [comment]
你到现在还没明白并发数量和qps(每秒执行多少次)之间的区别，并发数量只有在函数耗时刚好精确等于1秒时候才等于qps。
