### ISSUE TITLE
任务监控，没有下发任务

### ISSUE THREAD

**Issue by xmydjx** [Boris-code/feapder#135]
![image](https://user-images.githubusercontent.com/47141266/142368081-63346834-496e-417b-b6e8-b85f5266b592.png)

start_monitor_task任务监控，没有下发任务，而数据库没有任务，这是什么原因，最后显示“start_requests无任务添加”

**Comment by Boris-code** [comment]
那个sql 能查出来数据么，断点调试下

**Comment by xmydjx** [comment]
> 那个sql能查出来数据么，断点调试下

可以查出数据，但现在数据库没有数据，我想添加任务数据进去

**Comment by HtForBetterLife** [comment]
请问解决了吗？
