### ISSUE TITLE
有没有考虑过将多线程改为aiohttp

### ISSUE THREAD

**Issue by sirliu** [Boris-code/feapder#137]
亲测用aiohttp比多线程（100线程），1000个目标，要快8倍。

**Comment by Boris-code** [comment]
测试代码发下瞅瞅

**Comment by sirliu** [comment]
> 测试代码发下瞅瞅

```python
import feapder,json,time

url='http://www.baidu.com'
#url='http://ssr1.scrape.center/'
class AirSpiderDemo(feapder.AirSpider):
    def start_requests(self):
        for i in range(1000):
            yield feapder.Request(url, verify=False, method="get")


    def parse(self, request, response):
        pass
#################################################################################################### aiohttp测试
from aiohttp import ClientSession,TCPConnector
import asyncio


async def make_request(client):
    async with client.get(url) as resp:
        s=await resp.text()
        # print(s)
        return s
 
async def main():
    # cons = TCPConnector(limit=11)connector=cons
    async with ClientSession() as client:
        starttime = time.time()
        tasks = [asyncio.create_task(make_request(client)) for _ in range(1000)]
        s = await asyncio.gather(*tasks)
        endtime = time.time()
        print(f"QOS:{len(tasks)/(endtime-starttime)}")
        return s


if __name__ == '__main__':
    # s = time.time()
    # AirSpiderDemo(thread_count=100).start()
    # print('feapder:',time.time()-s)
    ####### aiohttp ########
    start = time.time()
    s=asyncio.run(main()) # jupyter 环境使用 await main ()
    # print(len(s))
    end = time.time()
    print(f'aiohttp：{end - start}')
```

**Comment by Boris-code** [comment]
你这个测试代码 aiohttp部分是1000并发，框架是500并发，且框架还需要各种调度，所以慢了些，如果测试上万的请求，其实差不多的。按照你这个例子，我写了面这个，测试了下线程和协程的效率，你可以试试

本地搭建服务，避免网络波动
```
from flask import Flask
import time

app = Flask(__name__)


@app.route("/", methods=["GET"])
def index():
    time.sleep(2)
    return "hello"


if __name__ == "__main__":
    app.run(debug=False, host="0.0.0.0", port=8081)

```

测试代码
```
import asyncio

import feapder
import requests
import time
from aiohttp import ClientSession

url = "http://localhost:8081"
import threading


class AirSpiderDemo(feapder.AirSpider):
    __custom_setting__ = dict(
        LOG_LEVEL="ERROR",
        RANDOM_HEADERS=False,
        USE_SESSION=True
    )
    def start_requests(self):
        for i in range(500):
            yield feapder.Request(url, verify=False, method="get", use_session=True)

    def parse(self, request, response):
        print(response.text[:32])

    def start_callback(self):
        self.s = time.time()

    def end_callback(self):
        print("总耗时", time.time() - self.s)

#################################################################################################### requests 测试


def test_requests():
    resp = requests.get(url)
    print(resp.text[:32])


def test_thread():
    threads = []
    starttime = time.time()
    for i in range(500):
        thread = threading.Thread(target=test_requests)
        threads.append(thread)
        thread.start()

    for thread in threads:
        thread.join()

    print(f"{time.time() - starttime}")


#################################################################################################### aiohttp 测试


async def make_request(client):
    async with client.get(url) as resp:
        s = await resp.text()
        print(s[:32])


async def test_aiohttp():
    async with ClientSession() as client:
        starttime = time.time()
        tasks = [asyncio.create_task(make_request(client)) for _ in range(500)]
        s = await asyncio.gather(*tasks)
        endtime = time.time()
        print(f"QOS:{len(tasks) / (endtime - starttime)}")
        print(f"{endtime - starttime}")
        return s


if __name__ == "__main__":
    AirSpiderDemo(thread_count=500).start() # 8.3
    # s=asyncio.run(test_aiohttp()) # 10.27
    # test_thread() # 3

```

**Comment by sirliu** [comment]
> 你这个测试代码 aiohttp部分是1000并发，框架是500并发，且框架还需要各种调度，所以慢了些，如果测试上万的请求，其实差不多的。按照你这个例子，我写了面这个，测试了下线程和协程的效率，你可以试试
> 
> 本地搭建服务，避免网络波动
> 
> ```
> from flask import Flask
> import time
> 
> app = Flask(__name__)
> 
> 
> @app.route("/", methods=["GET"])
> def index():
>     time.sleep(2)
>     return "hello"
> 
> 
> if __name__ == "__main__":
>     app.run(debug=False, host="0.0.0.0", port=8081)
> ```
> 
> 测试代码
> 
> ```
> import asyncio
> 
> import feapder
> import requests
> import time
> from aiohttp import ClientSession
> 
> url = "http://localhost:8081"
> import threading
> 
> 
> class AirSpiderDemo(feapder.AirSpider):
>     __custom_setting__ = dict(
>         LOG_LEVEL="ERROR",
>         RANDOM_HEADERS=False,
>         USE_SESSION=True
>     )
>     def start_requests(self):
>         for i in range(500):
>             yield feapder.Request(url, verify=False, method="get", use_session=True)
> 
>     def parse(self, request, response):
>         print(response.text[:32])
> 
>     def start_callback(self):
>         self.s = time.time()
> 
>     def end_callback(self):
>         print("总耗时", time.time() - self.s)
> 
> #################################################################################################### requests 测试
> 
> 
> def test_requests():
>     resp = requests.get(url)
>     print(resp.text[:32])
> 
> 
> def test_thread():
>     threads = []
>     starttime = time.time()
>     for i in range(500):
>         thread = threading.Thread(target=test_requests)
>         threads.append(thread)
>         thread.start()
> 
>     for thread in threads:
>         thread.join()
> 
>     print(f"{time.time() - starttime}")
> 
> 
> #################################################################################################### aiohttp 测试
> 
> 
> async def make_request(client):
>     async with client.get(url) as resp:
>         s = await resp.text()
>         print(s[:32])
> 
> 
> async def test_aiohttp():
>     async with ClientSession() as client:
>         starttime = time.time()
>         tasks = [asyncio.create_task(make_request(client)) for _ in range(500)]
>         s = await asyncio.gather(*tasks)
>         endtime = time.time()
>         print(f"QOS:{len(tasks) / (endtime - starttime)}")
>         print(f"{endtime - starttime}")
>         return s
> 
> 
> if __name__ == "__main__":
>     AirSpiderDemo(thread_count=500).start() # 8.3
>     # s=asyncio.run(test_aiohttp()) # 10.27
>     # test_thread() # 3
> ```

大赞！在局域网搭建服务测试了10万次请求，差距确实不大，feapder耗时290+，aiohttp耗时207+。
感谢大佬耐心解答。
