### ISSUE TITLE
给item属性赋值时，不支持datetime object。提示 Object of type datetime is not JSON serializable

### ISSUE THREAD

**Issue by kk-deng** [Boris-code/feapder#138]
在使用 datetime 库的时候，创建了一个对象。但是通过 Item 入MongoDB库的时候提示

> 2021-11-30 21:58:04.183 | DEBUG    | feapder.core.parser_control:run:464 - parser 等待任务...
2021-11-30 21:58:04.197 | ERROR    | feapder.utils.tools:dumps_json:844 - Object of type datetime is not JSON serializable
2021-11-30 21:58:04.201 | DEBUG    | feapder.buffer.item_buffer:__add_item_to_db:323 -

其中一个json内容是：

>  [{'_id': 2508352,
  'elapsed_mins': 1.0691154666666667,
  'first_post_time': '11-30 21:57',
  'first_post_time_obj': datetime.datetime(2021, 11, 30, 21, 57)...

但是在MongoDB上却能正常看到这个入库：

![image](https://user-images.githubusercontent.com/71301799/144165769-ebac78ec-8132-4689-bb7a-daf379d98aac.png)

搜了一下网上的。发现是 json.dumps 不支持这个类型，解决方法简单粗暴转换为 str，其中一个方法是添加 `default=str` 在对应部分。

> json.dumps(my_dictionary, indent=4, sort_keys=True, **default=str**)

不知道大佬觉得应该如何解决？实在不想转换到 str。。。。 多谢了！

**Comment by Boris-code** [comment]
这个错其实是不影响的，这是打印日志的时候为了好看，dump下，有捕获异常，所以你在mongo能看到数据
你这边建议是什么，加个`default=str`么，感觉也可以

**Comment by kk-deng** [comment]
> 这个错其实是不影响的，这是打印日志的时候为了好看，dump下，有捕获异常，所以你在mongo能看到数据 你这边建议是什么，加个`default=str`么，感觉也可以

多谢大佬回复。如果不影响的话我还是保留原来的格式好了。 `default=str` 会把所有不认识的转换为str。但我想的是接下来入库的时候可以在MongoDB里面直接以datetime的格式看统计数据了。stackoverflow上还有人是使用pymongo的内置util功能解决的：

> As you are using mongoengine (per comments) and pymongo is a dependency, pymongo has built-in utilities to help with 

> json serialization:
> http://api.mongodb.org/python/1.10.1/api/bson/json_util.html
> 
> Example usage (serialization):
> 

> from bson import json_util
> import json
> 
> json.dumps(anObject, default=json_util.default)
> Example usage (deserialization):
> 
> json.loads(aJsonString, object_hook=json_util.object_hook)

链接：https://stackoverflow.com/a/11875813

我也不太懂如何处理比较好。刚上手望见谅！

**Comment by kk-deng** [comment]
另外想问个问题，比较小的问题就不创建新的issue了。

我在使用 UpdateItem 对同一个网页里的内容爬取时候，如果遇到相同的内容，里面需要更新对应的点赞数。

日志里面显示已经更新了内容：

> 2021-11-30 22:46:26.772 | DEBUG    | feapder.buffer.item_buffer:__add_item_to_db:323 -
>                 -------------- item 批量更新 --------------
>                 表名: spider_data
>                 datas: [
>                 {
>                                 "_id": 2508350,
>                                 **"upvotes": 1,**
>                                 **"elapsed_mins": 54.4446175,**
>                                 "retailer_name": "Amazon.ca",
>                                 "topic_title": "Philips Fully Automatic Espresso Machines",
>                                 "first_post_time_obj": "2021-11-30 21:52:00",
>                                 "first_post_time": "11-30 21:52",
>                                 "reply_count": 2,
>                                 "view_count": 925,
>                                 "msg_sent_cnt": 0
>                 }
> ]
> 
> 2021-11-30 22:46:26.797 | INFO     | feapder.pipelines.mongo_pipeline:update_items:79 - 共导出 1 条数据到 spider_data,  新增 0 条, **更新 1  条** 更新字段为 ['upvotes', 'elapsed_mins', 'reply_count', 'view_count', 'msg_sent_cnt']

但是在MongoDB里面却没有更新，一直都是第一次入库时的信息（实际上这里的2已经变成1，而时间从40分钟变成上面的54分钟了）。我已经把这个字段填写在 __update_key__  中了，并没有作用。（_id 是唯一字段，在MongoDB中是primary key）

![image](https://user-images.githubusercontent.com/71301799/144169022-1c67b20c-32b1-4104-b144-fccbc7a6208f.png)


不知道是不是我还有什么设置有问题，望作者指点一下！多谢！

**Comment by Boris-code** [comment]
- mongo更新的问题 可能是你的feapder版本比较老，1.6.8之后的版本修复了这个问题
- json dumps的问题，刚发布了个版本 可更新解决

总结：更新feapder
```
pip install feapder==1.7.1b1
```

**Comment by kk-deng** [comment]
> * mongo更新的问题 可能是你的feapder版本比较老，1.6.8之后的版本修复了这个问题
> * json dumps的问题，刚发布了个版本 可更新解决
> 
> 总结：更新feapder
> 
> ```
> pip install feapder==1.7.1b1
> ```

神速啊！看来 `default=str` 确实能正确打印到日志并且在MongoDB中以datetime入库。

关于 MongoDB的问题，我前几天第一次安装，刚确认了一下是1.7.0 。在更新feapder到1.7.1b1后问题依旧。我现在去升级一下MongoDB看看问题能否解决。 再次感谢

**Comment by kk-deng** [comment]
更新：在feapder 1.7.1b1 和升级MongoDB Compass到1.29.5 并没有解决问题。依旧日志显示最新的数据，并且显示更新2条，但数据库里面还是首次入库的数据。

请问作者还需要什么信息吗？

**Comment by Boris-code** [comment]
之前都是设置索引来触发更新的，比如你的商品id单独一个字段，然后这个字段设置唯一，没直接用mongo的id。
刚改了下框架，处理了这种情况，你更新下试试
```
pip install feapder==1.7.1b2
```

**Comment by kk-deng** [comment]
多谢更新。

我本来是不直接用 MongoDB 的 _id 的，并且添加了 thread_id 作为一个字段并设置唯一。结果一直报错说找不到 thread_id _ （最后带下划线的） 的 index。。。（刚刚我才意识到必须要填写名字，它搜索的index是我填的名字而不是 key本身！如果有类似疑问的朋友，可以注意一下：）
![image](https://user-images.githubusercontent.com/71301799/144184562-e8d6f503-0faf-4788-99e8-befd2dc64435.png)


后来把我的 thread_id 改成 _id 来替换MongoDB的 _id （就是之前发的日志里用的）。结果依旧，能找到相同的记录，但数据一直不更新……

索引设置如下：
![image](https://user-images.githubusercontent.com/71301799/144184801-b65fc04c-ff35-466e-a0d4-b5ef2647f66d.png)

刷新后的内容：

> ...
>                 {
>                                 "_id": 2508388,
>                                 "thread_id": 2508388,
>                                 "upvotes": 18,
>                                 "elapsed_mins": 74.37094663333333,
>                                 "retailer_name": "[Various]",
>                                 "topic_title": "2021 holiday bonus gift card thread",
>                                 "first_post_time_obj": "2021-12-01 00:21:00",
>                                 "first_post_time": "12-01 00:21",
>                                 "reply_count": 4,
>                                 "view_count": 876,
>                                 "msg_sent_cnt": 0
>                 }
> ]
> 
> 2021-12-01 01:35:22.369 | INFO     | feapder.pipelines.mongo_pipeline:update_items:79 - 共导出 2 条数据到 spider_data,  新增 0 条, 更新 2 条 更新字段为 ['upvotes', 'elapsed_mins', 'reply_count', 'view_count', 'msg_sent_cnt']

然而同一个记录下，elapsed_mins没有更新到 74.37

![image](https://user-images.githubusercontent.com/71301799/144184995-cc52a022-9c6b-4a10-b618-7b055dd7624f.png)

**Comment by Boris-code** [comment]
现在可以了么

**Comment by kk-deng** [comment]
> 现在可以了么

久等了。如上面回复说的，两种id的方法都没有更新指定的key，依旧是只有第一次入库的内容。。。

**Comment by Boris-code** [comment]
我这测试是好使的，注意feapder版本为 1.7.1-beta2, 可在控制台输入feapder查看版本
测试代码
```
import feapder
from feapder import UpdateItem


class TestMongoPipeline(feapder.AirSpider):
    __custom_setting__ = dict(
        ITEM_PIPELINES=["feapder.pipelines.mongo_pipeline.MongoPipeline"],
        MONGO_IP="localhost",
        MONGO_PORT=27017,
        MONGO_DB="feapder",
        MONGO_USER_NAME="",
        MONGO_USER_PASS="",
    )

    def start_requests(self):
        yield feapder.Request("https://www.baidu.com")

    def parse(self, request, response):
        # 用id做唯一索引
        # item = UpdateItem()  # 声明一个item
        # item.table_name = "test_mongo2"
        # item._id = 1
        # item.data = 2
        # yield item  # 返回item， item会自动批量入库

        # 指定唯一索引
        item = UpdateItem()  # 声明一个item
        item.table_name = "test_mongo3"
        item.xxx_id = 1  # 先手动在库里将xxx_id设置唯一索引
        item.data = 4
        yield item  # 返回item， item会自动批量入库


if __name__ == "__main__":
    TestMongoPipeline().start()
```
测试代码运行两次，第二次时修改下data值，看是否更新

mongo索引
![image](https://user-images.githubusercontent.com/14087023/144344911-cdd9ab7e-276f-46f9-aaa0-505d210702fc.png)

**Comment by kk-deng** [comment]
多谢回复！版本号没错是 feapder 1.7.1-beta2

用了你的代码确实没问题，让我一直很困惑。刚我花了一个小时终于重现这个bug了。。。

**就是每次更新只会更新最后一列的数据**。比如上面代码的数据部分增加一列，改成：

```python
...
        # 指定唯一索引
        item = UpdateItem()  # 声明一个item
        item.table_name = "test_mongo3"
        item.xxx_id = 1  # 先手动在库里将xxx_id设置唯一索引
        item.data = 1
        item.data_2 = 1  # 增加这一列
        yield item  # 返回item， item会自动批量入库
...
```

如果把 `item.data` 和 `item.data_2` 都改成3，那最后只有  `item.data_2` 从1变成3， `item.data` 则保持不变依旧是1

如图：
![image](https://user-images.githubusercontent.com/71301799/144351486-cf6a2499-1ec9-4b19-b9de-f3901bbc139e.png)

数据库：
![image](https://user-images.githubusercontent.com/71301799/144351528-f335994b-57c4-4f8b-a0f2-e8a22d312aaf.png)


麻烦大佬再试试

**Comment by Boris-code** [comment]
pip install feapder==1.7.1b3

更新一波 再试试

**Comment by kk-deng** [comment]
速度啊！测试成功，bug修复了，目前看来是能正常更新了！非常感谢大佬的迅速修复bug！

有几个问题想请教

1. 如果要从 MongoDB 里面读取之前爬的数据是不是只能用 PyMongo来操作？好像没看到相关的函数。
2. 不知道能不能给轻量级爬虫的用户加上一个入库到csv等类似文件的pipeline功能？看了文档有人问起，但是大佬回复自己做，本人技术有限，想自定义一个但是不知道何从下手……
3. 如果只是想定时（比如每分钟）爬同一个网页，我现在实现方法是在这个请求函数下循环yield：
```python
    def start_requests(self):
        for i in range(30):
            yield feapder.Request("https://www.google.com/")
            time.sleep(random.randrange(60, 120))
```
想问一下有什么更好的实现方法吗？

再次感谢大佬的帮助 ^^
