### ISSUE TITLE
是否兼容scrapy的DEPTH_LIMIT 

### ISSUE THREAD

**Issue by kevinzhangcode** [Boris-code/feapder#151]
注意到，`Scrapy`有[DEPTH_LIMIT,DEPTH_PRIORITY](https://docs.scrapy.org/en/latest/topics/settings.html?highlight=depth#std-setting-DEPTH_LIMIT)系列参数，用于控制深度，请问feader是否有类似的设计呢?

**Comment by Boris-code** [comment]
没有，可以自己在Request中携带层级参数，如 yield feapder.Request(..., depth=1), 然后层级递增 yield feapder.Request(..., depth=2)
