### ISSUE TITLE
日志重复输出

### ISSUE THREAD

**Issue by xihacode** [Boris-code/feapder#158]
![image](https://user-images.githubusercontent.com/14148974/178107302-52d509a7-9d9c-42a6-b511-f5792ded52ee.png)
控制台会重复输出相同的日子

**Comment by ShellMonster** [comment]
我也遇到了，使用方法就只是这样，重新生成项目也不行：
```python
from feapder.utils.log import log

log.info("输出内容")
```

**Comment by pgshow** [comment]
loggru 在多线程，多进程的有些情况下有问题，有些是某些库引起的。
