### ISSUE TITLE
AttributeError: type object 'DesiredCapabilities' has no attribute 'PHANTOMJS'

### ISSUE THREAD

**Issue by mindonmindon** [Boris-code/feapder#171]
It  happened where running with PHANTOMJS

2022-09-15 14:13:05.176 | ERROR    | logging:exception:line:1481 | type object 'DesiredCapabilities' has no attribute 'PHANTOMJS'
Traceback (most recent call last):

  File "D:\Users\yl3594\AppData\Local\Programs\Python\Python38\lib\threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x000001FE46188CA0>
    └ <AirSpiderParserControl(Thread-3, started 8388)>

  File "D:\Users\yl3594\AppData\Local\Programs\Python\Python38\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
    │    └ <function AirSpiderParserControl.run at 0x000001FE48EAD040>
    └ <AirSpiderParserControl(Thread-3, started 8388)>

  File "F:\own\snapshot_spider\venv\lib\site-packages\feapder\core\parser_control.py", line 458, in run
    self.deal_request(request)
    │    │            └ <Request https://www.baidu.com>
    │    └ <function AirSpiderParserControl.deal_request at 0x000001FE48EAD0D0>
    └ <AirSpiderParserControl(Thread-3, started 8388)>

> File "F:\own\snapshot_spider\venv\lib\site-packages\feapder\core\parser_control.py", line 524, in deal_request
    request.get_response()
    │       └ <function Request.get_response at 0x000001FE48EAB4C0>
    └ <Request https://www.baidu.com>

  File "F:\own\snapshot_spider\venv\lib\site-packages\feapder\network\request.py", line 354, in get_response
    response = self.render_downloader.download(self)
               │    │                 │        └ <Request https://www.baidu.com>
               │    │                 └ <function SeleniumDownloader.download at 0x000001FE48EA2CA0>
               │    └ <feapder.network.downloader._selenium.SeleniumDownloader object at 0x000001FE4868A880>
               └ <Request https://www.baidu.com>

  File "F:\own\snapshot_spider\venv\lib\site-packages\feapder\network\downloader\_selenium.py", line 46, in download
    browser = self._webdriver_pool.get(user_agent=user_agent, proxy=proxy)
              │    │                              │                 └ None
              │    │                              └ 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1985.67 Safari/537.36'
              │    └ <property object at 0x000001FE48CC2EA0>
              └ <feapder.network.downloader._selenium.SeleniumDownloader object at 0x000001FE4868A880>

  File "F:\own\snapshot_spider\venv\lib\site-packages\feapder\utils\webdriver.py", line 465, in get
    driver = WebDriver(**kwargs)
             │           └ {'load_images': False, 'user_agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0....
             └ <class 'feapder.utils.webdriver.WebDriver'>

  File "F:\own\snapshot_spider\venv\lib\site-packages\feapder\utils\webdriver.py", line 144, in __init__
    self.driver = self.phantomjs_driver()
    │             │    └ <function WebDriver.phantomjs_driver at 0x000001FE48EA2430>
    │             └ <unprintable WebDriver object>
    └ <unprintable WebDriver object>

  File "F:\own\snapshot_spider\venv\lib\site-packages\feapder\utils\webdriver.py", line 337, in phantomjs_driver
    dcap = DesiredCapabilities.PHANTOMJS
           └ <class 'selenium.webdriver.common.desired_capabilities.DesiredCapabilities'>

AttributeError: type object 'DesiredCapabilities' has no attribute 'PHANTOMJS'
2022-09-15 14:13:05.180 | ERROR    | feapder.core.parser_control:deal_request:line:603 | 
                            -------------- XueQiuSpider.parse error -------------
                            error          type object 'DesiredCapabilities' has no attribute 'PHANTOMJS'
                            response       None
                            deal request   {
                            "url": "https://www.baidu.com",
                            "method": "GET",
                            "retry_times": 10,
                            "parser_name": "XueQiuSpider",
                            "filter_repeat": false,
                            "render": true,
                            "error_msg": "AttributeError: type object 'DesiredCapabilities' has no attribute 'PHANTOMJS'",
                            "response": "None"
}

**Comment by Boris-code** [comment]
试试这个版本 selenium==3.141.0
