### ISSUE TITLE
1.7.9无法指定类型创建爬虫

### ISSUE THREAD

**Issue by fgetwewr** [Boris-code/feapder#172]
>feapder create -s first_spider 3                         
usage: feapder [-h] [-p] [-s] [-i] [-t] [-init] [-j] [-sj] [-c] [--params] [--setting] [--host] [--port] [--username] [--password] [--db]
feapder: error: unrecognized arguments: 3

**Comment by Boris-code** [comment]
不用指定类型， 直接 feapder create -s first_spider  然后再根据提示选择

**Comment by fgetwewr** [comment]
应该怎么选择呢，尝试了一些按键，切换不了爬虫模板

**Comment by fgetwewr** [comment]
试了，没反应，光标一直停留在AirSpider
![image](https://user-images.githubusercontent.com/40048028/190537544-90e30d06-25f2-4ecd-b3f0-fdcea04dcc0e.png)

**Comment by Boris-code** [comment]
啥环境，加微信说吧，boris_tm

**Comment by Boris-code** [comment]
已修复
