### ISSUE TITLE
渲染模式报错：Promise was collected

### ISSUE THREAD

**Issue by lanyuer** [Boris-code/feapder#173]
本机测用 selenium抓同一个页面没有问题的

报错信息：

`2022-09-16 18:55:24.067 | ERROR    | feapder.core.parser_control:deal_request:line:603 | 
                            -------------- First.parse error -------------
                            error          Message: unknown error: unhandled inspector error: {"code":-32000,"message":"Promise was collected"}
  (Session info: headless chrome=105.0.5195.125)
Stacktrace:
#0 0x557a4c1cc693 <unknown>
#1 0x557a4bfc5b0a <unknown>
#2 0x557a4bfb2a1c <unknown>
#3 0x557a4bfb122d <unknown>
#4 0x557a4bfb150c <unknown>
#5 0x557a4bfd0965 <unknown>
#6 0x557a4bfc8568 <unknown>
#7 0x557a4bfc8252 <unknown>
#8 0x557a4bfc89ab <unknown>
#9 0x557a4bfc8cbc <unknown>
#10 0x557a4c0317a7 <unknown>
#11 0x557a4c01b922 <unknown>
#12 0x557a4c02f4b0 <unknown>
#13 0x557a4c01b743 <unknown>
#14 0x557a4bff1533 <unknown>
#15 0x557a4bff2715 <unknown>
#16 0x557a4c21c7bd <unknown>
#17 0x557a4c21fbf9 <unknown>
#18 0x557a4c201f2e <unknown>
#19 0x557a4c2209b3 <unknown>
#20 0x557a4c1f5e4f <unknown>
#21 0x557a4c23fea8 <unknown>
#22 0x557a4c240052 <unknown>
#23 0x557a4c25a71f <unknown>
#24 0x7f02564be609 <unknown>

                            response       None
                            deal request   {
                            "url": "https://www.baidu.com/s?wd=%A1%B6%CE%D2%B0%D6%B0%D6%A1%B7%BB%E6%B1%BE+%B8%E6%CB%DF%CE%D2%C3%C7%CA%B2%C3%B4%B5%C0%C0%ED&cl=3",
                            "method": "GET",
                            "retry_times": 2,
                            "parser_name": "First",
                            "callback": "parse",
                            "filter_repeat": false,
                            "render": true,
                            "error_msg": "selenium.common.exceptions.WebDriverException: Message: unknown error: unhandled inspector error: {\"code\":-32000,\"message\":\"Promise was collected\"}\n  (Session info: headless chrome=105.0.5195.125)\nStacktrace:\n#0 0x562582776693 <unknown>\n#1 0x56258256fb0a <unknown>\n#2 0x56258255ca1c <unknown>\n#3 0x56258255b22d <unknown>\n#4 0x56258255b50c <unknown>\n#5 0x56258257a965 <unknown>\n#6 0x562582572568 <unknown>\n#7 0x562582572252 <unknown>\n#8 0x5625825729ab <unknown>\n#9 0x562582572cbc <unknown>\n#10 0x5625825db7a7 <unknown>\n#11 0x5625825c5922 <unknown>\n#12 0x5625825d94b0 <unknown>\n#13 0x5625825c5743 <unknown>\n#14 0x56258259b533 <unknown>\n#15 0x56258259c715 <unknown>\n#16 0x5625827c67bd <unknown>\n#17 0x5625827c9bf9 <unknown>\n#18 0x5625827abf2e <unknown>\n#19 0x5625827ca9b3 <unknown>\n#20 0x56258279fe4f <unknown>\n#21 0x5625827e9ea8 <unknown>\n#22 0x5625827ea052 <unknown>\n#23 0x56258280471f <unknown>\n#24 0x7f0d2250c609 <unknown>\n",
                            "response": "None"
}`

**Comment by Boris-code** [comment]
上代码
