### ISSUE TITLE
How to use playwright in batchspider mode?

### ISSUE THREAD

**Issue by lycanthropes** [Boris-code/feapder#175]
I have copied  codes from test_playwright.py in a bacthspider script, and it worked wrong with warning: "It looks like you are using Playwright Sync API inside the asyncio loop. Please use the Async API instead." I known test_playwright plays well in Airspider demo, does there exist a bacthspider demo using palywright?

**Comment by Boris-code** [comment]
use 
spider.run()
or
spider.start()
spider.join()

**Comment by kk-deng** [comment]
```python
2022-10-08 21:08:19.784 | ERROR    | logging:exception:line:1481 | 'LazyProperty' object has no attribute 'close_all'
Traceback (most recent call last):

  File "c:/Users/xxxx/Projects/test\demo_playwright.py", line 42, in <module>
    TestPlaywright(thread_count=1).run()
    └ <class '__main__.TestPlaywright'>

> File "C:\Users\xxxx\miniconda3\envs\daily38\lib\site-packages\feapder\core\spiders\air_spider.py", line 101, in run
    Request.render_downloader.close_all()
    │       └ <classmethod object at 0x0000026B8AFF3310>
    └ <class 'feapder.network.request.Request'>

AttributeError: 'LazyProperty' object has no attribute 'close_all'
```

@Boris-code 想借地问问，我升级到 feapder-1.8.0b6 然后运行  test_playwright.py 结果报这个错误，如果我单独使用 PlayWright 的代码来运行则没问题。有什么可能的原因吗？

**Comment by Boris-code** [comment]
> ```python
> 2022-10-08 21:08:19.784 | ERROR    | logging:exception:line:1481 | 'LazyProperty' object has no attribute 'close_all'
> Traceback (most recent call last):
> 
>   File "c:/Users/xxxx/Projects/test\demo_playwright.py", line 42, in <module>
>     TestPlaywright(thread_count=1).run()
>     └ <class '__main__.TestPlaywright'>
> 
> > File "C:\Users\xxxx\miniconda3\envs\daily38\lib\site-packages\feapder\core\spiders\air_spider.py", line 101, in run
>     Request.render_downloader.close_all()
>     │       └ <classmethod object at 0x0000026B8AFF3310>
>     └ <class 'feapder.network.request.Request'>
> 
> AttributeError: 'LazyProperty' object has no attribute 'close_all'
> ```
> 
> @Boris-code 想借地问问，我升级到 feapder-1.8.0b6 然后运行 test_playwright.py 结果报这个错误，如果我单独使用 PlayWright 的代码来运行则没问题。有什么可能的原因吗？

你的python版本不支持这个语法，升级到feapder==1.8.3可以解决
