### ISSUE TITLE
分布式环境下GoldUserPool如何控制一个账号的使用频率

### ISSUE THREAD

**Issue by luoshun1** [Boris-code/feapder#176]
我看 GoldUserPool.get_user 是通过读取账号池的所有账号放到本地, 再循环从本地池子pop出账号的. 如果爬虫是分布式的, 怎么保证一个账号不会同时被使用呢? 是需要自己另外实现吗?

**Comment by Boris-code** [comment]
支持分布式的，直接用就好

**Comment by luoshun1** [comment]
多个进程同时通过 redisdb.hkeys 拿到一份所有账号, 放入各自进程的 _users_id 里面, 每个进程每次从自己的 _users_id 里面pop一个账号使用, 多进程下是存在重复使用的吧? 是我看的代码的位置不对吗?

**Comment by Boris-code** [comment]
可能你没看明白，可以实际操作下试试
