### ISSUE TITLE
render=True的时候，使用xhr_url_regexes会报错：RecursionError: maximum recursion depth exceeded

### ISSUE THREAD

**Issue by 9cij** [Boris-code/feapder#180]
m2芯片，经过调试，定位到问题产生的地方为feapder/utils/webdriver/selenium_driver.py的78行，self.driver_type,改成_driver_type就可以了<img width="1232" alt="image" src="https://user-images.githubusercontent.com/51077648/199899417-86b1151c-add1-4dff-8357-6fb4e6e3b37d.png">

**Comment by Boris-code** [comment]
好的，修复了 feapder==1.8.3
