### ISSUE TITLE
运行 Feapder 时遇到 It looks like you are using Playwright Sync API inside the asyncio loop.

### ISSUE THREAD

**Issue by pgshow** [Boris-code/feapder#185]
**需知**
环境：Ubuntu20, Python3.8， 我已经解决该问题分享到这里。

**问题**
运行 Feapder 时遇到 It looks like you are using Playwright Sync API inside the asyncio loop.

其实这个问题是 Playwright 没有安装依赖组件造成的，如果运行一个简易测试案例，你会发现以下提示:

_sudo playwright install-deps_  的字样

**此时只要使用使用命令：**

> python3 -m playwright install-deps

然后在运行  feapder 就可以了。

**Comment by Boris-code** [comment]
感谢，果然好用
没安装时可以使用run方法运行
```
spider = XxxSpider(...)
spider.run()
```
安装后可以使用 spider.start() 运行了
