### ISSUE TITLE
python3.11环境下无法使用

### ISSUE THREAD

**Issue by Foreverpy** [Boris-code/feapder#188]
电脑安装的python版本为3.11，使用feapder创建任务出现错误

![image](https://user-images.githubusercontent.com/91273504/202112255-b90b5a56-557c-48ea-b10c-736ff4d5c7aa.png)
在3.11的更新文档中，发现已将`getargspec()`函数移除，希望可以更新适配3.11的版本
![image](https://user-images.githubusercontent.com/91273504/202113201-d3eb0b5c-af73-43af-a613-b787f6af46ac.png)

**Comment by Foreverpy** [comment]
3.11版本对re模块有修改，`(?!)`语法不能正常使用
![image](https://user-images.githubusercontent.com/91273504/202371917-8afba075-0d00-4169-aaf0-43376a14ac5f.png)

我做了一些调整，供参考
![image](https://user-images.githubusercontent.com/91273504/202372485-09a4bcef-5a4d-49ee-953c-8b3082936d02.png)

**Comment by RuixiangS** [comment]
可以提个pull request

**Comment by Boris-code** [comment]
可以提个pull request + 1

**Comment by suyin-long** [comment]
我用的也是Python3.11.0，使用feapder创建任务没有报错，但是运行feapder爬虫脚本时报错：
```
error          global flags not at the start of the expression at position 2
```
这是怎么回事？

**Comment by Boris-code** [comment]
升级到1.8.6b6

**Comment by suyin-long** [comment]
> 升级到1.8.6b6

这个是稳定版吗？默认装的是feapder 1.8.5，然后我用Python 3.10.10试了下可以正常使用。待会用Python 3.11试试你说的这个feapder版本。
