### ISSUE TITLE
使用代理时诡异的连接失败的问题

### ISSUE THREAD

**Issue by pgshow** [Boris-code/feapder#194]
**问题**
在 python3.8.x 下， feapder 所有版本都有这个问题，当使用某些IP白名单 ssl 代理时，会遇到各种连接不上代理服务器的错误。

错误会有很多种，我遇到的：443错误，1133 错误，握手超时 等

**解决方法**
安装完所有包后，卸载 urllib3，并安装 1.26 以下的低版本，这样就可以正常使用 ssl 代理了。
pip uninstall urllib3
pip install urllib3==1.25.11

**Comment by Boris-code** [comment]
这个问题其实文档已经写啦 https://feapder.com/#/question/%E8%AF%B7%E6%B1%82%E9%97%AE%E9%A2%98
