### ISSUE TITLE
mysqldb close_connection问题

### ISSUE THREAD

**Issue by danerlt** [Boris-code/feapder#195]
**需知**

升级feapder，保证feapder是最新版，若BUG仍然存在，则详细描述问题
> pip install --upgrade feapder

**问题**
当数据库连接失败的时候,conn,和cursor未返回,调用close_connection会报错
**截图**
![image](https://user-images.githubusercontent.com/14197717/206942881-e0775f10-ee89-4afe-9e36-736878eef90e.png)

**代码**
feapder.db.mysqldb.py文件

建议在try之前定义conn,cursor,再close_connection加入判断如下:

```python
    def close_connection(self, conn, cursor):
        if conn:
            cursor.close()
        if cursor:
            conn.close()
```

**Comment by Boris-code** [comment]
OK
