### ISSUE TITLE
[Bug]: close_browser not working

### ISSUE THREAD

**Issue by BeanWei** [Boris-code/feapder#197]
**问题**
close_browser 无效，关闭headless时，可以看到旧的浏览器实例没有被关闭，新的浏览器实例无法打开新的页面，一直停留在 `data;`这个url上

**代码**

```python
def parse(self, request, response):
    response.close_browser(request)
```

-----
**Update:**
我把 `thread_safe` 打开时它才是work的

**Comment by Linsanxian** [comment]
> thread_safe
如何打开？

**Comment by duanhao123** [comment]
我也想问，是怎么打开thrad_safe，咋解决的

**Comment by Linsanxian** [comment]
> 我也想问，是怎么打开thrad_safe，咋解决的

我之前我记着解决了~ 但是时间太久了，找不见代码了.
是在这个框架上弄的

**Comment by Linsanxian** [comment]
> 我也想问，是怎么打开thrad_safe，咋解决的

![image](https://github.com/user-attachments/assets/d56b4c02-b522-4efc-8386-edcac472bce4)
看代码是在这里
