### ISSUE TITLE
怎么把数据保存为CSV文件？

### ISSUE THREAD

**Issue by liuchangfu** [Boris-code/feapder#216]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Boris-code** [comment]
看下https://feapder.com/#/source_code/pipeline

**Comment by liuchangfu** [comment]
> 



> 看下https://feapder.com/#/source_code/pipeline

看得不是很明白 ，那两个参数是怎么传过来的？能解释一下吗？

**Comment by liuchangfu** [comment]
> 

研究出来了，谢谢。这个框架比那个scrapy好用多了。文档也写得很清晰，易学，容易上手。
