### ISSUE TITLE
在使用playwright的时候总是报错，sync_playwright().start()这里会报错

### ISSUE THREAD

**Issue by rottengeek** [Boris-code/feapder#220]
![iShot_2023-04-26_01 24 33](https://user-images.githubusercontent.com/38384303/234355044-e8f0808d-b65c-4207-a2aa-10d59e91099d.png)

报错如下：
signal only works in main thread  第一次运行
it looks like you are using playwright sync api inside the asyncio loop 第二次运行

好像应该要使用异步接口

**Comment by hijack911** [comment]
我也是, 遇到了这个问题

**Comment by Boris-code** [comment]
使用spider.run方法运行爬虫
