### ISSUE TITLE
UpdateItem 批量更新数据问题

### ISSUE THREAD

**Issue by oyjcmyn** [Boris-code/feapder#221]
例如，数据表 共字段 id,name,pic,time ，id字段自增，其它字段默认为0，
如果现在使用UpdateItem，同时更新两条数据时，
数据结构是：datas[{'name':'xxx',"pic":'ccc'},{'name':'bbb',"pic":'ttt','time':'2020-12-12'}]
这样就会报错，报 time字段不能为null,

其实表中字段都设置有默认值，但是如果默认不是设置的null，就会有这错误。主要也是因为更新两条数据以上时，数据字段数不一样导致。有没有什么办法避免。

**Comment by oyjcmyn** [comment]
如果是一条一条的更新它是没有问题的

**Comment by Boris-code** [comment]
批量更新要求保持数据结构一致
