### ISSUE TITLE
mysql 查询 有bug 

### ISSUE THREAD

**Issue by heqiang** [Boris-code/feapder#239]
**问题**
当我查询数据的时候， to_json=True,limit=1 时，如果查询结果为[] 就会报错
**截图**
![1695716425606](https://github.com/Boris-code/feapder/assets/40254331/253d8b6e-f115-4aa8-9e2d-73580f051d18)

**代码**
没有判断result 为空的情况
 if limit == 1:
                if conver_col:
                    result = [convert(col) for col in result]
                result = dict(zip(columns, result))
```python

```

**Comment by Boris-code** [comment]
好的，已修复，下个版本发布

**Comment by Boris-code** [comment]
feapder==1.9.0b1

已发布
