### ISSUE TITLE
 feapder requests能支持curl_cffi类似绕过指纹吗

### ISSUE THREAD

**Issue by yuzhegan** [Boris-code/feapder#247]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by suyin-long** [comment]
自定义下载中间件可以实现

**Comment by shouge** [comment]
是的 可以通过自定义下载中间件来实现 框架自身预留扩展机制
