### ISSUE TITLE
爬虫断掉 重连一直使用旧代理IP 

### ISSUE THREAD

**Issue by huangwenyan1225** [Boris-code/feapder#48]
爬虫断掉 重连一直使用旧代理IP    导致一直重试爬取失败   代理IP能配置重连重新获取？

**Comment by huangwenyan1225** [comment]
还有配置的PROXY_EXTRACT_API 返回json 不是ip:port格式  这个配置就用不了

**Comment by Boris-code** [comment]
> 爬虫断掉 重连一直使用旧代理IP 导致一直重试爬取失败 代理IP能配置重连重新获取？

为了节省代理，不是每次重启都重新获取，只有代理不能用了才会获取。一直失败不用管，等他把代理消耗完了就会获取了

**Comment by Boris-code** [comment]
> 还有配置的PROXY_EXTRACT_API 返回json 不是ip:port格式 这个配置就用不了

不支持json，只支持下面这种。 你可以在下载中间件里加代理， request.proxies={"https":"https:xxx.xxx.xxx.xxx:xxxx", "http":"http:xxx.xxx.xxx.xxx:xxxx"}
58.218.201.74:3036
58.218.201.74:2584
58.218.201.122:8817
58.218.201.114:6452
58.218.201.74:2641
58.218.201.122:5837
58.218.201.74:4890
58.218.201.122:5992
58.218.201.122:5905
58.218.201.122:7357
