### ISSUE TITLE
集成批次爬虫，任务消费完后没有更新批次完成进度导致批次卡死

### ISSUE THREAD

**Issue by AlanWeekend** [Boris-code/feapder#53]
![image](https://user-images.githubusercontent.com/24834613/114903901-d9def180-9e49-11eb-8458-9afb4b8214e7.png)
![image](https://user-images.githubusercontent.com/24834613/114903965-ed8a5800-9e49-11eb-92eb-e60b33161e4f.png)

一共三个任务，都执行完之后，批次进度还是0。

一直在提示正在取丢失任务。取的是正在抓取的任务state=2，而我所有的任务都已经执行完了state=1。一直取不到，一直卡在这里
![image](https://user-images.githubusercontent.com/24834613/114905574-af8e3380-9e4b-11eb-90fc-07f235ef234e.png)

![image](https://user-images.githubusercontent.com/24834613/114905516-9c7b6380-9e4b-11eb-9525-85b11509981e.png)

**Comment by Boris-code** [comment]
> ![image](https://user-images.githubusercontent.com/24834613/114903901-d9def180-9e49-11eb-8458-9afb4b8214e7.png)
> ![image](https://user-images.githubusercontent.com/24834613/114903965-ed8a5800-9e49-11eb-92eb-e60b33161e4f.png)
> 
> 一共三个任务，都执行完之后，批次进度还是0。
> 
> 一直在提示正在取丢失任务。取的是正在抓取的任务state=2，而我所有的任务都已经执行完了state=1。一直取不到，一直卡在这里
> ![image](https://user-images.githubusercontent.com/24834613/114905574-af8e3380-9e4b-11eb-90fc-07f235ef234e.png)
> 
> ![image](https://user-images.githubusercontent.com/24834613/114905516-9c7b6380-9e4b-11eb-9525-85b11509981e.png)

你的批次是不是小时级别的，是的话看下你的批次表， batch_date字段类型是不是datetime
天为批次 batch_date字段类型为date， 小时分钟级别的为datetime。 
你可能是之前是天的级别，后来改成小时了

**Comment by AlanWeekend** [comment]
原来如此 tks

**Comment by AlanWeekend** [comment]
![image](https://user-images.githubusercontent.com/24834613/115176492-cd83be80-a0ff-11eb-8536-a98452d6d5fc.png)
批次时间这里我已经改成datetime了
![image](https://user-images.githubusercontent.com/24834613/115176523-de343480-a0ff-11eb-81d9-86cc23cd06f9.png)
代码里配置的是1/24

执行代码时，插入的记录里 批次时间只精确到小时。
![image](https://user-images.githubusercontent.com/24834613/115176630-0e7bd300-a100-11eb-906d-88f72affc273.png)
任务消费完之后，一直提示有丢失的任务。然后没有等待1小时，直接开始了下一个批次。这是哪里的问题？

**Comment by AlanWeekend** [comment]
忘记更新task了 打扰了
