### ISSUE TITLE
通过request传递参数失败

### ISSUE THREAD

**Issue by AndrewAndrea** [Boris-code/feapder#55]
![image](https://user-images.githubusercontent.com/35560234/115187016-36c1fc80-a115-11eb-8167-fd31b8803259.png)

按照这个例子写的，

但是提示没有这个参数 `task_id`

**Comment by Boris-code** [comment]
> ![image](https://user-images.githubusercontent.com/35560234/115187016-36c1fc80-a115-11eb-8167-fd31b8803259.png)
> 
> 按照这个例子写的，
> 
> 但是提示没有这个参数 `task_id`

可能是你派发新请求时，没携带task_id, 也可能是你之前redis里有没携带task_id的任务

**Comment by AndrewAndrea** [comment]
我的是自己 `for` 循环生成的，不是这个. 而且确定是有值的

**Comment by AndrewAndrea** [comment]
> > ![图像](https://user-images.githubusercontent.com/35560234/115187016-36c1fc80-a115-11eb-8167-fd31b8803259.png)
> > 按照这个例子写的，
> > 但是提示没有这个参数 `task_id`
> 
> 可能是你派发新请求时，没携带task_id，也可能是你之前redis里有没携带task_id的任务

![image](https://user-images.githubusercontent.com/35560234/115188074-f1063380-a116-11eb-94da-045a069bd41e.png)
这样的，

**Comment by AndrewAndrea** [comment]
大佬，还有个问题，为啥在 `parse` 里打印是可以的。但是在 `start_request` 打印 使用 `print`,就没有呢

**Comment by AndrewAndrea** [comment]
> > > ![图像](https://user-images.githubusercontent.com/35560234/115187016-36c1fc80-a115-11eb-8167-fd31b8803259.png)
> > > 按照这个例子写的，
> > > 但是提示没有这个参数`task_id`
> > 
> > 
> > 可能是你派发新请求时，没携带task_id，也可能是你之前redis里有没携带task_id的任务
> 
> ![图像](https://user-images.githubusercontent.com/35560234/115188074-f1063380-a116-11eb-94da-045a069bd41e.png)
> 这样的，

![image](https://user-images.githubusercontent.com/35560234/115188603-bd77d900-a117-11eb-8b9d-4191e36d626c.png)

**Comment by Boris-code** [comment]
> > > > ![图像](https://user-images.githubusercontent.com/35560234/115187016-36c1fc80-a115-11eb-8167-fd31b8803259.png)
> > > > 按照这个例子写的，
> > > > 但是提示没有这个参数`task_id`
> > > 
> > > 
> > > 可能是你派发新请求时，没携带task_id，也可能是你之前redis里有没携带task_id的任务
> > 
> > 
> > ![图像](https://user-images.githubusercontent.com/35560234/115188074-f1063380-a116-11eb-94da-045a069bd41e.png)
> > 这样的，
> 
> ![image](https://user-images.githubusercontent.com/35560234/115188603-bd77d900-a117-11eb-8b9d-4191e36d626c.png)

放下你的全部代码，这个片段看起来没问题。 另外可以先研究下代码示例， 没问题了再自己写

**Comment by AndrewAndrea** [comment]
> > > > > ![图像](https://user-images.githubusercontent.com/35560234/115187016-36c1fc80-a115-11eb-8167-fd31b8803259.png)
> > > > > 按照这个例子写的，
> > > > > 但是提示没有这个参数`task_id`
> > > > 
> > > > 
> > > > 可能是你派发新请求时，没携带task_id，也可能是你之前redis里有没携带task_id的任务
> > > 
> > > 
> > > ![图像](https://user-images.githubusercontent.com/35560234/115188074-f1063380-a116-11eb-94da-045a069bd41e.png)
> > > 这样的，
> > 
> > 
> > ![图像](https://user-images.githubusercontent.com/35560234/115188603-bd77d900-a117-11eb-8b9d-4191e36d626c.png)
> 
> 放下你的全部代码，这个片段看起来没问题。另外可以先研究下代码示例，没问题了再自己写

```python
# -*- coding: utf-8 -*-
"""
Created on 2021-04-16 11:02:45
---------
@summary:
---------
@author: Administrator
"""

import feapder

city_list = [
    {"name": "\u5e7f\u4e1c",
     "city": ["\u5e7f\u5dde", "\u6df1\u5733", "\u73e0\u6d77", "\u6f6e\u5dde", "\u4e2d\u5c71", "\u4e1c\u839e",
              "\u4f5b\u5c71", "\u60e0\u5dde", "\u6c55\u5934", "\u6c55\u5c3e", "\u97f6\u5173", "\u6e5b\u6c5f",
              "\u8087\u5e86", "\u6cb3\u6e90", "\u6c5f\u95e8", "\u63ed\u9633", "\u8302\u540d", "\u6885\u5dde",
              "\u6e05\u8fdc", "\u9633\u6c5f", "\u4e91\u6d6e"]},
    {"name": "\u6d59\u6c5f", "city": ["\u676d\u5dde", "\u5b81\u6ce2", "\u6e29\u5dde", "\u7ecd\u5174",
                                      "\u53f0\u5dde", "\u5609\u5174",
                                      "\u91d1\u534e", "\u4e3d\u6c34",
                                      "\u6e56\u5dde", "\u8862\u5dde",
                                      "\u821f\u5c71"]}]


class ParkSpider(feapder.Spider):

    headers = {
        "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:82.0) Gecko/20100101 Firefox/82.0"
    }
    # self.url = "https://www.baidu.com/s?ie=UTF-8&wd={}%20{}&pn={}"
    url = "https://www.baidu.com/s?wd={} {}&pn={}&oq={} {}"

    def start_requests(self):
        park_name_list = ["经济技术开发区", "高新技术开发区", "产业园", "工业园"]
        for city in city_list:
            city_name_list = city.get('city')
            province_name = city.get('name')
            for city_name in city_name_list:
                for park_name in park_name_list:
                    parmas = f'site:(.gov.cn) {park_name} "{city_name}"'
                    urls = [self.url.format(parmas, city_name, i, parmas, city_name) for i in range(0, 300, 10)]
                    for url in urls:
                        print(type(province_name), type(city_name), type(park_name))
                        yield feapder.Request(url, park_name=park_name)

    def parse(self, request, response):
        # city_name = request.city_name
        park_name = request.park_name
```
就是看着示例代码写的。文档也看过了，源码也看了。

**Comment by Boris-code** [comment]
> > > > > > ![图像](https://user-images.githubusercontent.com/35560234/115187016-36c1fc80-a115-11eb-8167-fd31b8803259.png)
> > > > > > 按照这个例子写的，
> > > > > > 但是提示没有这个参数`task_id`
> > > > > 
> > > > > 
> > > > > 可能是你派发新请求时，没携带task_id，也可能是你之前redis里有没携带task_id的任务
> > > > 
> > > > 
> > > > ![图像](https://user-images.githubusercontent.com/35560234/115188074-f1063380-a116-11eb-94da-045a069bd41e.png)
> > > > 这样的，
> > > 
> > > 
> > > ![图像](https://user-images.githubusercontent.com/35560234/115188603-bd77d900-a117-11eb-8b9d-4191e36d626c.png)
> > 
> > 
> > 放下你的全部代码，这个片段看起来没问题。另外可以先研究下代码示例，没问题了再自己写
> 
> ```python
> # -*- coding: utf-8 -*-
> """
> Created on 2021-04-16 11:02:45
> ---------
> @summary:
> ---------
> @author: Administrator
> """
> 
> import feapder
> 
> city_list = [
>     {"name": "\u5e7f\u4e1c",
>      "city": ["\u5e7f\u5dde", "\u6df1\u5733", "\u73e0\u6d77", "\u6f6e\u5dde", "\u4e2d\u5c71", "\u4e1c\u839e",
>               "\u4f5b\u5c71", "\u60e0\u5dde", "\u6c55\u5934", "\u6c55\u5c3e", "\u97f6\u5173", "\u6e5b\u6c5f",
>               "\u8087\u5e86", "\u6cb3\u6e90", "\u6c5f\u95e8", "\u63ed\u9633", "\u8302\u540d", "\u6885\u5dde",
>               "\u6e05\u8fdc", "\u9633\u6c5f", "\u4e91\u6d6e"]},
>     {"name": "\u6d59\u6c5f", "city": ["\u676d\u5dde", "\u5b81\u6ce2", "\u6e29\u5dde", "\u7ecd\u5174",
>                                       "\u53f0\u5dde", "\u5609\u5174",
>                                       "\u91d1\u534e", "\u4e3d\u6c34",
>                                       "\u6e56\u5dde", "\u8862\u5dde",
>                                       "\u821f\u5c71"]}]
> 
> 
> class ParkSpider(feapder.Spider):
> 
>     headers = {
>         "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:82.0) Gecko/20100101 Firefox/82.0"
>     }
>     # self.url = "https://www.baidu.com/s?ie=UTF-8&wd={}%20{}&pn={}"
>     url = "https://www.baidu.com/s?wd={} {}&pn={}&oq={} {}"
> 
>     def start_requests(self):
>         park_name_list = ["经济技术开发区", "高新技术开发区", "产业园", "工业园"]
>         for city in city_list:
>             city_name_list = city.get('city')
>             province_name = city.get('name')
>             for city_name in city_name_list:
>                 for park_name in park_name_list:
>                     parmas = f'site:(.gov.cn) {park_name} "{city_name}"'
>                     urls = [self.url.format(parmas, city_name, i, parmas, city_name) for i in range(0, 300, 10)]
>                     for url in urls:
>                         print(type(province_name), type(city_name), type(park_name))
>                         yield feapder.Request(url, park_name=park_name)
> 
>     def parse(self, request, response):
>         # city_name = request.city_name
>         park_name = request.park_name
> ```
> 
> 就是看着示例代码写的。文档也看过了，源码也看了。

你没其他地方`yield feapder.Request`了？

**Comment by AndrewAndrea** [comment]
没有啊，就这一个，报错我就没再往下写了

**Comment by AndrewAndrea** [comment]
> > > > > > > ![图像](https://user-images.githubusercontent.com/35560234/115187016-36c1fc80-a115-11eb-8167-fd31b8803259.png)
> > > > > > > 按照这个例子写的，
> > > > > > > 但是提示没有这个参数`task_id`
> > > > > > 
> > > > > > 
> > > > > > 可能是你派发新请求时，没携带task_id，也可能是你之前redis里有没携带task_id的任务
> > > > > 
> > > > > 
> > > > > ![图像](https://user-images.githubusercontent.com/35560234/115188074-f1063380-a116-11eb-94da-045a069bd41e.png)
> > > > > 这样的，
> > > > 
> > > > 
> > > > ![图像](https://user-images.githubusercontent.com/35560234/115188603-bd77d900-a117-11eb-8b9d-4191e36d626c.png)
> > > 
> > > 
> > > 放下你的全部代码，这个片段看起来没问题。另外可以先研究下代码示例，没问题了再自己写
> > 
> > 
> > ```python
> > # -*- coding: utf-8 -*-
> > """
> > Created on 2021-04-16 11:02:45
> > ---------
> > @summary:
> > ---------
> > @author: Administrator
> > """
> > 
> > import feapder
> > 
> > city_list = [
> >     {"name": "\u5e7f\u4e1c",
> >      "city": ["\u5e7f\u5dde", "\u6df1\u5733", "\u73e0\u6d77", "\u6f6e\u5dde", "\u4e2d\u5c71", "\u4e1c\u839e",
> >               "\u4f5b\u5c71", "\u60e0\u5dde", "\u6c55\u5934", "\u6c55\u5c3e", "\u97f6\u5173", "\u6e5b\u6c5f",
> >               "\u8087\u5e86", "\u6cb3\u6e90", "\u6c5f\u95e8", "\u63ed\u9633", "\u8302\u540d", "\u6885\u5dde",
> >               "\u6e05\u8fdc", "\u9633\u6c5f", "\u4e91\u6d6e"]},
> >     {"name": "\u6d59\u6c5f", "city": ["\u676d\u5dde", "\u5b81\u6ce2", "\u6e29\u5dde", "\u7ecd\u5174",
> >                                       "\u53f0\u5dde", "\u5609\u5174",
> >                                       "\u91d1\u534e", "\u4e3d\u6c34",
> >                                       "\u6e56\u5dde", "\u8862\u5dde",
> >                                       "\u821f\u5c71"]}]
> > 
> > 
> > class ParkSpider(feapder.Spider):
> > 
> >     headers = {
> >         "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:82.0) Gecko/20100101 Firefox/82.0"
> >     }
> >     # self.url = "https://www.baidu.com/s?ie=UTF-8&wd={}%20{}&pn={}"
> >     url = "https://www.baidu.com/s?wd={} {}&pn={}&oq={} {}"
> > 
> >     def start_requests(self):
> >         park_name_list = ["经济技术开发区", "高新技术开发区", "产业园", "工业园"]
> >         for city in city_list:
> >             city_name_list = city.get('city')
> >             province_name = city.get('name')
> >             for city_name in city_name_list:
> >                 for park_name in park_name_list:
> >                     parmas = f'site:(.gov.cn) {park_name} "{city_name}"'
> >                     urls = [self.url.format(parmas, city_name, i, parmas, city_name) for i in range(0, 300, 10)]
> >                     for url in urls:
> >                         print(type(province_name), type(city_name), type(park_name))
> >                         yield feapder.Request(url, park_name=park_name)
> > 
> >     def parse(self, request, response):
> >         # city_name = request.city_name
> >         park_name = request.park_name
> > ```
> > 
> > 
> > 就是看着示例代码写的。文档也看过了，源码也看了。
> 
> 你没其他地方`yield feapder.Request`了？

就一个，就start_request，
