### ISSUE TITLE
WebDriver的render_time参数如何设置对集成批次爬虫中的所有任务生效

### ISSUE THREAD

**Issue by AlanWeekend** [Boris-code/feapder#66]
我在配置文件中设置render_time，似乎只对第一个任务生效，剩下的任务并没有等待，直接执行parse了

**Comment by Boris-code** [comment]
> 我在配置文件中设置render_time，似乎只对第一个任务生效，剩下的任务并没有等待，直接执行parse了

嗯嗯， 找到bug了， 下一版发布解决

**Comment by AlanWeekend** [comment]
辛苦多谢
