### ISSUE TITLE
有没有办法为item分别指定pipeline呢

### ISSUE THREAD

**Issue by QinJun-1998** [Boris-code/feapder#77]
在解析中我可能要生成两种Item，然后存储到不同的数据库
这意味着不同的Item走不同的Pipeline
如果我定义了两个Pipeline，目前来看，好像是item会走一遍所有的Pipeline
有没有办法比如让两个Item各自走各自的Pipeline

**Comment by mkdir700** [comment]
暂时的解决办法：可以在每个`pipeline`里做一个判断

**Comment by QinJun-1998** [comment]
> 暂时的解决办法：可以在每个`pipeline`里做一个判断

对，我也是这样想的，但是我整的好像挺麻烦。在定义pipeline的save_items方法的时候，参数Items是一个列表，列表里是多个item字典，我试了一下，这个列表里的item没有了类属性？应该是这样描述吧我也不太懂，比如我实例化了两个Item，我本来是想用isinstance来判断这个item来自哪个，但实际上这个列表里的item都不能据此判断，彷佛这个列表里的Item就是字典而不是某个类实例化出来的，所以这条路我没走通，后来我直接给item赋一个新的键值对来标识，但问题又来了，这个新的键值对数据库里是没有这个字段的，所以我在pipeline里判断完之后又删除了这个键值对，然后当走另一个pipeline时，我发现这个pipeline接收的item是前一个pipeline处理过的，也就是删掉这个标识键值对后的Item.然后我又操作改了一下，才最后实现了。是不是挺麻烦哈哈，不知道有没有更简便或者说更稳的方法~

**Comment by Boris-code** [comment]
> > 暂时的解决办法：可以在每个`pipeline`里做一个判断
> 
> 对，我也是这样想的，但是我整的好像挺麻烦。在定义pipeline的save_items方法的时候，参数Items是一个列表，列表里是多个item字典，我试了一下，这个列表里的item没有了类属性？应该是这样描述吧我也不太懂，比如我实例化了两个Item，我本来是想用isinstance来判断这个item来自哪个，但实际上这个列表里的item都不能据此判断，彷佛这个列表里的Item就是字典而不是某个类实例化出来的，所以这条路我没走通，后来我直接给item赋一个新的键值对来标识，但问题又来了，这个新的键值对数据库里是没有这个字段的，所以我在pipeline里判断完之后又删除了这个键值对，然后当走另一个pipeline时，我发现这个pipeline接收的item是前一个pipeline处理过的，也就是删掉这个标识键值对后的Item.然后我又操作改了一下，才最后实现了。是不是挺麻烦哈哈，不知道有没有更简便或者说更稳的方法~

为啥你们不用table_name判断

**Comment by QinJun-1998** [comment]
打扰了

**Comment by mkdir700** [comment]
这个是存储不同的数据库，还是不同的数据表

**Comment by QinJun-1998** [comment]
> 这个是存储不同的数据库，还是不同的数据表

库。如果是相同的库准备存不同的表，那不是只需要一个pipeline和两个item，不需要判断item走那个pipeline。

**Comment by mkdir700** [comment]
ui

> > 这个是存储不同的数据库，还是不同的数据表
> 
> 库。如果是相同的库准备存不同的表，那不是只需要一个pipeline和两个item，不需要判断item走那个pipeline。

是的，同处于一个库，在一个pipeline内判断即可

**Comment by QinJun-1998** [comment]
额，同处于一个库的话不是item.table_name这个已经定义了要存入的表，不需要再在pipeline里额外的判断了

**Comment by mkdir700** [comment]
确实，我想多了

**Comment by QinJun-1998** [comment]
你这么一提我到想到了，如果两个不同数据库里的表的名字是一样的，那么根据table_name来判断pipeline应该使用哪个item的方法也失效了。还好我现在用的不一样~

**Comment by mkdir700** [comment]
如果是两个库的话，在`pipeline`的`__init__`方法内可以多建立一个数据库连接

**Comment by QinJun-1998** [comment]
> 如果是两个库的话，在`pipeline`的`__init__`方法内可以多建立一个另一个库的连接

对，这样也行，不过有点强迫症，我觉得拆成两个pipeline比较规范一点哈哈

**Comment by mkdir700** [comment]
> > 如果是两个库的话，在`pipeline`的`__init__`方法内可以多建立一个另一个库的连接
> 
> 对，这样也行，不过有点强迫症，我觉得拆成两个pipeline比较规范一点哈哈

我觉得可行

**Comment by Boris-code** [comment]
> > 如果是两个库的话，在`pipeline`的`__init__`方法内可以多建立一个另一个库的连接
> 
> 对，这样也行，不过有点强迫症，我觉得拆成两个pipeline比较规范一点哈哈

这种需求场景是啥，有实际例子没

**Comment by QinJun-1998** [comment]
> > > 如果是两个库的话，在`pipeline`的`__init__`方法内可以多建立一个另一个库的连接
> > 
> > 
> > 对，这样也行，不过有点强迫症，我觉得拆成两个pipeline比较规范一点哈哈
> 
> 这种需求场景是啥，有实际例子没
这个场景应该不常见。。主要是我图方便，把多个爬虫融合在一起了。我有一批产品ID，要爬取这些产品的详情然后这个详情里面有这个产品所在的类目排行榜的url，我也要爬取这个url下面的所有产品ID然后再爬取这些ID的详情，也就是我们称的竞品的详情。我用了批次爬虫，所有的详情存储存在sql server（接手过来的），然后我就是图省事只用一个爬虫，就把爬到的类目url添加到任务表（mysql），类目url爬取解析出新的产品ID后又存到这个任务表，然后，就这样了，所以写了两个存储的pipeline，一个存新来的任务一个存任务的结果
