### ISSUE TITLE
递归调用 feapder.Request 时 url 存在遗漏

### ISSUE THREAD

**Issue by KerwinChen** [Boris-code/feapder#81]
目前想完成一个需求：爬取目标网站的所有 URL。代码如下：

```python
class UrlSpider(feapder.AirSpider):
    def start_requests(self):
        yield feapder.Request("https://example.cn")

    def parse(self, request, response):
        print(response.url)
        url_list = response.re("<a.*?href='(.*?)'")
        for url in url_list:
            # print(url)
            if response.url in url:
                yield feapder.Request(url, callback=self.parse)
```

这样调用的时候，url_list 中的 url 只有部分进入 `feapder.Request` 中。
同时设置 `REQUEST_FILTER_ENABLE = True` 后，似乎也没有生效。
是否我的使用方式存在问题？

PS：像 Scrapy 的 Link extractor 一样的效果。

**Comment by Boris-code** [comment]
> ```python
> class UrlSpider(feapder.AirSpider):
>     def start_requests(self):
>         yield feapder.Request("https://example.cn")
> 
>     def parse(self, request, response):
>         print(response.url)
>         url_list = response.re("<a.*?href='(.*?)'")
>         for url in url_list:
>             # print(url)
>             if response.url in url:
>                 yield feapder.Request(url, callback=self.parse)
> ```

任务没有丢，可能是你统计错了, 我统计的方法如下
```python

import feapder


class UrlSpider(feapder.AirSpider):
    urls = []
    def start_requests(self):
        yield feapder.Request("https://baidu.com")

    def parse(self, request, response):
        url_list = response.re("<a.*?href='(.*?)'")
        print(len(url_list))
        for url in url_list:
            yield feapder.Request(url, callback=self.parse2, auto_request=False)

    def parse2(self, request, response):
        self.__class__.urls.append(request.url)

    def end_callback(self):
        print(len(self.__class__.urls))


if __name__ == "__main__":
    UrlSpider().start()
```

> 同时设置 REQUEST_FILTER_ENABLE = True 后，似乎也没有生效
AirSpider不支持这个， Spider可以

**Comment by KerwinChen** [comment]
> > ```python
> > class UrlSpider(feapder.AirSpider):
> >     def start_requests(self):
> >         yield feapder.Request("https://example.cn")
> > 
> >     def parse(self, request, response):
> >         print(response.url)
> >         url_list = response.re("<a.*?href='(.*?)'")
> >         for url in url_list:
> >             # print(url)
> >             if response.url in url:
> >                 yield feapder.Request(url, callback=self.parse)
> > ```
> 
> 任务没有丢，可能是你统计错了, 我统计的方法如下
> 
> ```python
> import feapder
> 
> 
> class UrlSpider(feapder.AirSpider):
>     urls = []
>     def start_requests(self):
>         yield feapder.Request("https://baidu.com")
> 
>     def parse(self, request, response):
>         url_list = response.re("<a.*?href='(.*?)'")
>         print(len(url_list))
>         for url in url_list:
>             yield feapder.Request(url, callback=self.parse2, auto_request=False)
> 
>     def parse2(self, request, response):
>         self.__class__.urls.append(request.url)
> 
>     def end_callback(self):
>         print(len(self.__class__.urls))
> 
> 
> if __name__ == "__main__":
>     UrlSpider().start()
> ```
> 
> > 同时设置 REQUEST_FILTER_ENABLE = True 后，似乎也没有生效
> > AirSpider不支持这个， Spider可以

好的。我尝试看看。我没有多写一个 parse 的原因是网站可能有很多层，所以就直接 callback 默认的 parse 来递归调用。

**Comment by Boris-code** [comment]
> > > ```python
> > > class UrlSpider(feapder.AirSpider):
> > >     def start_requests(self):
> > >         yield feapder.Request("https://example.cn")
> > > 
> > >     def parse(self, request, response):
> > >         print(response.url)
> > >         url_list = response.re("<a.*?href='(.*?)'")
> > >         for url in url_list:
> > >             # print(url)
> > >             if response.url in url:
> > >                 yield feapder.Request(url, callback=self.parse)
> > > ```
> > 
> > 
> > 任务没有丢，可能是你统计错了, 我统计的方法如下
> > ```python
> > import feapder
> > 
> > 
> > class UrlSpider(feapder.AirSpider):
> >     urls = []
> >     def start_requests(self):
> >         yield feapder.Request("https://baidu.com")
> > 
> >     def parse(self, request, response):
> >         url_list = response.re("<a.*?href='(.*?)'")
> >         print(len(url_list))
> >         for url in url_list:
> >             yield feapder.Request(url, callback=self.parse2, auto_request=False)
> > 
> >     def parse2(self, request, response):
> >         self.__class__.urls.append(request.url)
> > 
> >     def end_callback(self):
> >         print(len(self.__class__.urls))
> > 
> > 
> > if __name__ == "__main__":
> >     UrlSpider().start()
> > ```
> > 
> > 
> > > 同时设置 REQUEST_FILTER_ENABLE = True 后，似乎也没有生效
> > > AirSpider不支持这个， Spider可以
> 
> 好的。我尝试看看。我没有多写一个 parse 的原因是网站可能有很多层，所以就直接 callback 默认的 parse 来递归调用。

知道，懂你的意思，不多不是不好统计丢没丢么， 我就拆出来了

**Comment by Boris-code** [comment]
> 另外还想咨询一下。使用 Spider 后，同一个任务第二次运行就不爬取了，只有下面这样的提示
> 
> ```
> UrlSpider|2021-05-07 22:28:19,524|scheduler.py|<lambda>|line:108|INFO| 
> ********** feapder begin **********
> UrlSpider|2021-05-07 22:28:22,562|scheduler.py|<lambda>|line:113|INFO| 
> ********** feapder end **********
> UrlSpider|2021-05-07 22:28:22,564|scheduler.py|spider_end|line:504|INFO| 《feapder:url_spider》爬虫结束，耗时 3秒
> ```
> 
> 我加上了 `delete_keys=True` 也没效果。得去 redis 里面 `flushdb` 再运行爬虫才有执行的过程。这是我哪一步没做到位呢？

你是不是开启去重了

**Comment by KerwinChen** [comment]
对。我以为去重是作用在定期执行任务的场景下。每次新启动爬虫的时候没办法重新爬吗？

**Comment by Boris-code** [comment]
> 对。我以为去重是作用在定期执行任务的场景下。每次新启动爬虫的时候没办法重新爬吗？

那你就用内存去重，或者启动时清空去重库
