### ISSUE TITLE
浏览器渲染自动化失败处理

### ISSUE THREAD

**Issue by chenpython** [Boris-code/feapder#84]
解决方案：https://github.com/SergeyPirogov/webdriver_manager
安装 pip install webdriver-manager
from webdriver_manager.chrome import ChromeDriverManager
![截图](https://user-images.githubusercontent.com/45593480/117754595-37017380-b24d-11eb-9550-58b2d0fb27c6.png)
添加webdriver-manager库，完美解决。

**Comment by Boris-code** [comment]
> 解决方案：https://github.com/SergeyPirogov/webdriver_manager
> 安装 pip install webdriver-manager
> from webdriver_manager.chrome import ChromeDriverManager
> ![截图](https://user-images.githubusercontent.com/45593480/117754595-37017380-b24d-11eb-9550-58b2d0fb27c6.png)
> 添加webdriver-manager库，完美解决。

解决啥问题了？？？？？

**Comment by chenpython** [comment]
> > 解决方案：https://github.com/SergeyPirogov/webdriver_manager
> > 安装 pip install webdriver-manager
> > from webdriver_manager.chrome import ChromeDriverManager
> > ![截图](https://user-images.githubusercontent.com/45593480/117754595-37017380-b24d-11eb-9550-58b2d0fb27c6.png)
> > 添加webdriver-manager库，完美解决。
> 
> 解决啥问题了？？？？？

找不到驱动和不启动浏览器
