### ISSUE TITLE
启动爬虫失败，提示 redis_lock 等待加锁

### ISSUE THREAD

**Issue by D1rtyDann** [Boris-code/feapder#88]
日志如下:
```
Taptap|2021-05-18 11:33:44,939|redis_lock.py|acquire|line:98|DEBUG| 等待加锁: <RedisLock: redis_lock:feapder:yinghuo:spider:taptap:dev:101 index: -1> wait:0.004386186599731445
Taptap|2021-05-18 11:33:49,951|redis_lock.py|acquire|line:98|DEBUG| 等待加锁: <RedisLock: redis_lock:feapder:yinghuo:spider:taptap:dev:101 index: -1> wait:5.0166754722595215
Taptap|2021-05-18 11:33:54,969|redis_lock.py|acquire|line:98|DEBUG| 等待加锁: <RedisLock: redis_lock:feapder:yinghuo:spider:taptap:dev:101 index: -1> wait:10.034656763076782
Taptap|2021-05-18 11:33:59,988|redis_lock.py|acquire|line:98|DEBUG| 等待加锁: <RedisLock: redis_lock:feapder:yinghuo:spider:taptap:dev:101 index: -1> wait:15.053444385528564
Taptap|2021-05-18 11:34:05,006|redis_lock.py|acquire|line:98|DEBUG| 等待加锁: <RedisLock: redis_lock:feapder:yinghuo:spider:taptap:dev:101 index: -1> wait:20.07160449028015
Taptap|2021-05-18 11:34:10,016|redis_lock.py|acquire|line:98|DEBUG| 等待加锁: <RedisLock: redis_lock:feapder:yinghuo:spider:taptap:dev:101 index: -1> wait:25.08188557624817
Taptap|2021-05-18 11:34:15,028|redis_lock.py|acquire|line:98|DEBUG| 等待加锁: <RedisLock: redis_lock:feapder:yinghuo:spider:taptap:dev:101 index: -1> wait:30.09346604347229
Taptap|2021-05-18 11:34:20,043|redis_lock.py|acquire|line:98|DEBUG| 等待加锁: <RedisLock: redis_lock:feapder:yinghuo:spider:taptap:dev:101 index: -1> wait:35.108797550201416
Taptap|2021-05-18 11:34:25,061|redis_lock.py|acquire|line:98|DEBUG| 等待加锁: <RedisLock: redis_lock:feapder:yinghuo:spider:taptap:dev:101 index: -1> wait:40.126882553100586
Taptap|2021-05-18 11:34:30,080|redis_lock.py|acquire|line:98|DEBUG| 等待加锁: <RedisLock: redis_lock:feapder:yinghuo:spider:taptap:dev:101 index: -1> wait:45.14540982246399
Taptap|2021-05-18 11:34:35,095|redis_lock.py|acquire|line:98|DEBUG| 等待加锁: <RedisLock: redis_lock:feapder:yinghuo:spider:taptap:dev:101 index: -1> wait:50.16076993942261
Taptap|2021-05-18 11:34:40,111|redis_lock.py|acquire|line:98|DEBUG| 等待加锁: <RedisLock: redis_lock:feapder:yinghuo:spider:taptap:dev:101 index: -1> wait:55.17621850967407
Taptap|2021-05-18 11:34:45,130|redis_lock.py|acquire|line:90|INFO| 加锁失败
Taptap|2021-05-18 11:34:48,164|scheduler.py|<lambda>|line:113|INFO| 
********** feapder end **********
Taptap|2021-05-18 11:34:48,206|scheduler.py|delete_tables|line:423|INFO| 正在删除key feapder:yinghuo:spider:taptap:dev:101:z_spider_status

进程已结束，退出代码为 0
```
使用 feapder create -s xxx 2 创建的爬虫。之前一两周都运行正常

**Comment by Boris-code** [comment]
> 日志如下:
> 
> ```
> Taptap|2021-05-18 11:33:44,939|redis_lock.py|acquire|line:98|DEBUG| 等待加锁: <RedisLock: redis_lock:feapder:yinghuo:spider:taptap:dev:101 index: -1> wait:0.004386186599731445
> Taptap|2021-05-18 11:33:49,951|redis_lock.py|acquire|line:98|DEBUG| 等待加锁: <RedisLock: redis_lock:feapder:yinghuo:spider:taptap:dev:101 index: -1> wait:5.0166754722595215
> Taptap|2021-05-18 11:33:54,969|redis_lock.py|acquire|line:98|DEBUG| 等待加锁: <RedisLock: redis_lock:feapder:yinghuo:spider:taptap:dev:101 index: -1> wait:10.034656763076782
> Taptap|2021-05-18 11:33:59,988|redis_lock.py|acquire|line:98|DEBUG| 等待加锁: <RedisLock: redis_lock:feapder:yinghuo:spider:taptap:dev:101 index: -1> wait:15.053444385528564
> Taptap|2021-05-18 11:34:05,006|redis_lock.py|acquire|line:98|DEBUG| 等待加锁: <RedisLock: redis_lock:feapder:yinghuo:spider:taptap:dev:101 index: -1> wait:20.07160449028015
> Taptap|2021-05-18 11:34:10,016|redis_lock.py|acquire|line:98|DEBUG| 等待加锁: <RedisLock: redis_lock:feapder:yinghuo:spider:taptap:dev:101 index: -1> wait:25.08188557624817
> Taptap|2021-05-18 11:34:15,028|redis_lock.py|acquire|line:98|DEBUG| 等待加锁: <RedisLock: redis_lock:feapder:yinghuo:spider:taptap:dev:101 index: -1> wait:30.09346604347229
> Taptap|2021-05-18 11:34:20,043|redis_lock.py|acquire|line:98|DEBUG| 等待加锁: <RedisLock: redis_lock:feapder:yinghuo:spider:taptap:dev:101 index: -1> wait:35.108797550201416
> Taptap|2021-05-18 11:34:25,061|redis_lock.py|acquire|line:98|DEBUG| 等待加锁: <RedisLock: redis_lock:feapder:yinghuo:spider:taptap:dev:101 index: -1> wait:40.126882553100586
> Taptap|2021-05-18 11:34:30,080|redis_lock.py|acquire|line:98|DEBUG| 等待加锁: <RedisLock: redis_lock:feapder:yinghuo:spider:taptap:dev:101 index: -1> wait:45.14540982246399
> Taptap|2021-05-18 11:34:35,095|redis_lock.py|acquire|line:98|DEBUG| 等待加锁: <RedisLock: redis_lock:feapder:yinghuo:spider:taptap:dev:101 index: -1> wait:50.16076993942261
> Taptap|2021-05-18 11:34:40,111|redis_lock.py|acquire|line:98|DEBUG| 等待加锁: <RedisLock: redis_lock:feapder:yinghuo:spider:taptap:dev:101 index: -1> wait:55.17621850967407
> Taptap|2021-05-18 11:34:45,130|redis_lock.py|acquire|line:90|INFO| 加锁失败
> Taptap|2021-05-18 11:34:48,164|scheduler.py|<lambda>|line:113|INFO| 
> ********** feapder end **********
> Taptap|2021-05-18 11:34:48,206|scheduler.py|delete_tables|line:423|INFO| 正在删除key feapder:yinghuo:spider:taptap:dev:101:z_spider_status
> 
> 进程已结束，退出代码为 0
> ```
> 
> 使用 feapder create -s xxx 2 创建的爬虫。之前一两周都运行正常

爬虫在执行start_requests之前会先获取锁，这是为了防止分布式爬虫同时下发任务。
你出现这个可能是之前任务下发时没下发完就停掉了爬虫，导致锁没释放。
解决办法有3种：
1. 等一个小时，锁会自动释放掉
2. spider传递wait_lock=False参数，不等待加锁，但这会直接执行start_requests，也就是说多个爬虫进程可能会导致任务添加重复。这个参数一般在开发时使用，上线时去掉
3. 去redis里把锁删掉， key为 redis_lock:爬虫名

**Comment by D1rtyDann** [comment]
已解决。谢谢作者。
