### ISSUE TITLE
输出日志问题

### ISSUE THREAD

**Issue by downdawn** [Boris-code/feapder#9]
![image](https://user-images.githubusercontent.com/41266749/108942969-ea1cf080-7692-11eb-8ef6-5ad11e8486aa.png)

一点意见

输出日志感觉有点混乱，特别是开了多线程之后
是否可以参考scrapy的日志格式，或者使用loguru用颜色来区分日志级别？

**Comment by Boris-code** [comment]
> ![image](https://user-images.githubusercontent.com/41266749/108942969-ea1cf080-7692-11eb-8ef6-5ad11e8486aa.png)
> 
> 一点意见
> 
> 输出日志感觉有点混乱，特别是开了多线程之后
> 是否可以参考scrapy的日志格式，或者使用loguru用颜色来区分日志级别？

您好，日志输出可以通过logger等级来修改。
默认是DEBUG，输出比较详细，开发阶段使用
INFO等级，日志会少很多，只会输出关键信息，线上环境使用

可通过配置文件中的 LOG_LEVEL 来配置
