### ISSUE TITLE
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 5985: character maps to <undefined>

### ISSUE THREAD

**Issue by guhailong18** [Boris-code/feapder#93]
# 解码似乎不够智能
代码如下：
from feapder import Request
class spider:
	def __init__(self,link):
		request = Request(link)
		response = request.get_response(save_cached=False)  # 缓存结果
		print(response.text)

if __name__ == '__main__':
	link1 = "https://www.kktv.me/titles/01000190"
	s1 = spider(link1)

## 完整报错
Traceback (most recent call last):
  File "D:/codeProject/python/spider_train/remind/base.py", line 30, in <module>
    s1 = spider(link1)
  File "D:/codeProject/python/spider_train/remind/base.py", line 7, in __init__
    print(response.text)
  File "D:\codeProject\python\venv\md\lib\site-packages\feapder\network\response.py", line 242, in text
    self._cached_text = self.__text
  File "D:\codeProject\python\venv\md\lib\site-packages\feapder\network\response.py", line 226, in __text
    content = str(self.content, self.encoding, errors=self.encoding_errors)
  File "D:\ProgramData\Miniconda3\lib\encodings\cp1254.py", line 15, in decode
    return codecs.charmap_decode(input,errors,decoding_table)
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 5985: character maps to <undefined>

**Comment by Boris-code** [comment]
> # 解码似乎不够智能
> 代码如下：
> from feapder import Request
> class spider:
> def **init**(self,link):
> request = Request(link)
> response = request.get_response(save_cached=False) # 缓存结果
> print(response.text)
> 
> if **name** == '**main**':
> link1 = "https://www.kktv.me/titles/01000190"
> s1 = spider(link1)
> 
> ## 完整报错
> Traceback (most recent call last):
> File "D:/codeProject/python/spider_train/remind/base.py", line 30, in
> s1 = spider(link1)
> File "D:/codeProject/python/spider_train/remind/base.py", line 7, in **init**
> print(response.text)
> File "D:\codeProject\python\venv\md\lib\site-packages\feapder\network\response.py", line 242, in text
> self._cached_text = self.__text
> File "D:\codeProject\python\venv\md\lib\site-packages\feapder\network\response.py", line 226, in __text
> content = str(self.content, self.encoding, errors=self.encoding_errors)
> File "D:\ProgramData\Miniconda3\lib\encodings\cp1254.py", line 15, in decode
> return codecs.charmap_decode(input,errors,decoding_table)
> UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 5985: character maps to

解码失败的可以手动指定下：比如之地你给utf-8  `response.code = "utf-8"`
