### ISSUE TITLE
TIEM - 能加数据类型校验功能吗

### ISSUE THREAD

**Issue by forgeries** [Boris-code/feapder#94]

**Comment by Boris-code** [comment]
> 能加上scrapy itemloader的数据处理功能就更好了

看下这个：https://boris.org.cn/feapder/#/source_code/Item?id=%e5%85%a5%e5%ba%93%e5%89%8d%e5%af%b9item%e8%bf%9b%e8%a1%8c%e5%a4%84%e7%90%86
