### ISSUE TITLE
下载缓存的使用

### ISSUE THREAD

**Issue by lscool66** [Boris-code/feapder#97]
在使用 **相同url** **不同 params json data** 传入参数时候会被认定为相同的request，当启用下载缓存的时候返回的结果都是第一次请求的数据，请问这是不是一个bug

**Comment by Boris-code** [comment]
> 在使用 **相同url** **不同 params json data** 传入参数时候会被认定为相同的request，当启用下载缓存的时候返回的结果都是第一次请求的数据，请问这是不是一个bug

贴你的代码

**Comment by lscool66** [comment]
`class BusLyAirspider(feapder.AirSpider):
    def start_requests(self):
        data = {
            "departure": "杭州",
            "destination": "杭州",
            "departureDate": "2021-06-05",
            "depId": "",
            "desId": "",
            "page": 1,
            "pageSize": 25,
            "orderTime": 0,
            "orderPrice": 0,
            "dptTimeSpan": "",
            "departureStation": "",
            "arrivalStation": "",
            "hasCategory": True
        }
        yield feapder.Request("https://bus.ly.com/busresapi/schedule/getScheduleList?plateId=3", json=data,
                              method="POST", verify=False)

    def parse(self, request, response):
        resp = response.json
        pageInfo = resp['body']['pageInfo']
        print(pageInfo)
        totalPage = pageInfo['totalPage']
        totalCount = pageInfo['totalCount']
        url = request.url
        data = request.json
        page = pageInfo['page']

        schedule = resp['body']['schedule']
        for i in schedule:
            # print(i)
            yield BusLyDataItem(**i)

        if page < totalPage:
            data['page'] = page+1
            yield feapder.Request(url=url, json=data, method="POST", verify=False)`

**Comment by lscool66** [comment]
`class BusLyAirspider(feapder.AirSpider):
    def start_requests(self):
        data = {
            "departure": "杭州",
            "destination": "杭州",
            "departureDate": "2021-06-05",
            "depId": "",
            "desId": "",
            "page": 1,
            "pageSize": 25,
            "orderTime": 0,
            "orderPrice": 0,
            "dptTimeSpan": "",
            "departureStation": "",
            "arrivalStation": "",
            "hasCategory": True
        }
        yield feapder.Request("https://bus.ly.com/busresapi/schedule/getScheduleList?plateId=3", json=data,
                              method="POST", verify=False)

    def parse(self, request, response):
        resp = response.json
        pageInfo = resp['body']['pageInfo']
        print(pageInfo)
        totalPage = pageInfo['totalPage']
        totalCount = pageInfo['totalCount']
        url = request.url
        data = request.json
        page = pageInfo['page']

        schedule = resp['body']['schedule']
        for i in schedule:
            # print(i)
            yield BusLyDataItem(**i)

        if page < totalPage:
            data['page'] = page+1
            yield feapder.Request(url=url, json=data, method="POST", verify=False)`

**Comment by lscool66** [comment]
```class BusLyAirspider(feapder.AirSpider):
    def start_requests(self):
        data = {
            "departure": "杭州",
            "destination": "杭州",
            "departureDate": "2021-06-05",
            "depId": "",
            "desId": "",
            "page": 1,
            "pageSize": 25,
            "orderTime": 0,
            "orderPrice": 0,
            "dptTimeSpan": "",
            "departureStation": "",
            "arrivalStation": "",
            "hasCategory": True
        }
        yield feapder.Request("https://bus.ly.com/busresapi/schedule/getScheduleList?plateId=3", json=data,
                              method="POST", verify=False)

    def parse(self, request, response):
        resp = response.json
        pageInfo = resp['body']['pageInfo']
        print(pageInfo)
        totalPage = pageInfo['totalPage']
        totalCount = pageInfo['totalCount']
        url = request.url
        data = request.json
        page = pageInfo['page']

        schedule = resp['body']['schedule']
        for i in schedule:
            # print(i)
            yield BusLyDataItem(**i)

        if page < totalPage:
            data['page'] = page+1
            yield feapder.Request(url=url, json=data, method="POST", verify=False)```

**Comment by Boris-code** [comment]
> ```
>     def start_requests(self):
>         data = {
>             "departure": "杭州",
>             "destination": "杭州",
>             "departureDate": "2021-06-05",
>             "depId": "",
>             "desId": "",
>             "page": 1,
>             "pageSize": 25,
>             "orderTime": 0,
>             "orderPrice": 0,
>             "dptTimeSpan": "",
>             "departureStation": "",
>             "arrivalStation": "",
>             "hasCategory": True
>         }
>         yield feapder.Request("https://bus.ly.com/busresapi/schedule/getScheduleList?plateId=3", json=data,
>                               method="POST", verify=False)
> 
>     def parse(self, request, response):
>         resp = response.json
>         pageInfo = resp['body']['pageInfo']
>         print(pageInfo)
>         totalPage = pageInfo['totalPage']
>         totalCount = pageInfo['totalCount']
>         url = request.url
>         data = request.json
>         page = pageInfo['page']
> 
>         schedule = resp['body']['schedule']
>         for i in schedule:
>             # print(i)
>             yield BusLyDataItem(**i)
> 
>         if page < totalPage:
>             data['page'] = page+1
>             yield feapder.Request(url=url, json=data, method="POST", verify=False)```
> ```

你的参数上下文互相影响了， 修改如下：
```
    def parse(self, request, response):
      
        data = copy.deepcopy(request.json)
```

**Comment by lscool66** [comment]
> > ```
> >     def start_requests(self):
> >         data = {
> >             "departure": "杭州",
> >             "destination": "杭州",
> >             "departureDate": "2021-06-05",
> >             "depId": "",
> >             "desId": "",
> >             "page": 1,
> >             "pageSize": 25,
> >             "orderTime": 0,
> >             "orderPrice": 0,
> >             "dptTimeSpan": "",
> >             "departureStation": "",
> >             "arrivalStation": "",
> >             "hasCategory": True
> >         }
> >         yield feapder.Request("https://bus.ly.com/busresapi/schedule/getScheduleList?plateId=3", json=data,
> >                               method="POST", verify=False)
> > 
> >     def parse(self, request, response):
> >         resp = response.json
> >         pageInfo = resp['body']['pageInfo']
> >         print(pageInfo)
> >         totalPage = pageInfo['totalPage']
> >         totalCount = pageInfo['totalCount']
> >         url = request.url
> >         data = request.json
> >         page = pageInfo['page']
> > 
> >         schedule = resp['body']['schedule']
> >         for i in schedule:
> >             # print(i)
> >             yield BusLyDataItem(**i)
> > 
> >         if page < totalPage:
> >             data['page'] = page+1
> >             yield feapder.Request(url=url, json=data, method="POST", verify=False)```
> > ```
> 
> 你的参数上下文互相影响了， 修改如下：
> ```
>     def parse(self, request, response):
>       
>         data = copy.deepcopy(request.json)
> ```
> 

收到，谢谢😜
