### ISSUE TITLE
mongodb单次插入数据大小不能超过16MB

### ISSUE THREAD

**Issue by mkdir700** [Boris-code/feapder#98]
[https://docs.mongodb.com/manual/reference/limits/#mongodb-limit-BSON-Document-Size](https://docs.mongodb.com/manual/reference/limits/#mongodb-limit-BSON-Document-Size)

**Comment by mkdir700** [comment]
😅😅 应该不会有单个item能超过16MB的大小吧

**Comment by Boris-code** [comment]
> 😅😅 应该不会有单个item能超过16MB的大小吧

单个的不会

**Comment by mkdir700** [comment]
收集器，收集的上限是5000条数据。

**Comment by mkdir700** [comment]
那5000条有可能不

**Comment by Boris-code** [comment]
> 那5000条有可能不

有可能
